// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @notice Generated by art/gen-sol-data.mjs from art/swarmlings.js and art/salt.json. Do not edit.
library SwarmlingsData {
    uint256 internal constant SUPPLY = 3333;
    bytes32 internal constant SALT = 0x011ecad7d0b8a52e4b5e3edd97a38fa83743a5db7ab4446105af4dd40086eacd;

    /// trait order: Background, Chassis, Head, Visor, Signal, Headgear, Accessory
    bytes internal constant WEIGHTS = hex"12100f0d0c0b09050114100f0e0d0a090201181612100e0616120f0d0c0a0603011e1c1411051414100d0b0908020122100d0c0a090501";
    bytes internal constant OFFSETS = hex"0009121821262f37";

    bytes internal constant BACKGROUNDS = hex"141a332b18380e2f333a1f17e9dfc8cfeee3ddd2f3f6d3b80b0f1f";
    /// 5 colors per chassis: outline, shadow, base, light, highlight
    bytes internal constant CHASSIS = hex"0d3b3616695e25a08b5fd0b8c9f4ea4a1a129c3b25e0623ff59a7afde0d41f23573a43a86470e09ea7f5e1e4ff1f33103c611962922b97c25adcefc21e2328424b546f7a85a6b0bae6ebef33204d5e3d8c8f68c4bea0e6efe4fb5c5c7816161c2a2a354a4a5c8c8ca63d2a038a5d06d49a0ff5c84afff1bf2b30366b7580b8c2cce3e9efffffff";
    /// 24 rows x (x0, x1) per head, ffff where the row is empty
    bytes internal constant HEADS = hex"ffffffffffffffffffffffff07100611061106110611061106110611061106110710ffffffffffffffffffffffffffffffffffffffffffffffffffff080f071006110611061106110611061106110710080fffffffffffffffffffffffffffffffffffffffffffffffffffff0a0d080f071006110611061106110611061106110710ffffffffffffffffffffffffffffffffffffffffffffffffffff090e080f07100710071007100710071007100710080f090effffffffffffffffffffffffffffffffffffffffffffffffffff0710061106110611061106110611061106110710ffffffffffffffffffffffffffffffffffffffffffffffffffff07100611061106110611061106110710080f090e0a0dffffffffffffffffffffffffffff";
    bytes internal constant SIGNALS = hex"ffd23f5ef2e0ff5d8fa3ff6bffffff";
    bytes internal constant SIGNALS_DIM = hex"7c692d3377767c3451527d417c7d84";
    bytes internal constant SIGNALS_SCARF = hex"bf9e2f47b6a8bf466b7abf50bfbfbf";

    string internal constant NAMES_BACKGROUND = "Midnight|Plum|Abyss|Ember|Sand|Mint|Lilac|Peach|Grid";
    string internal constant NAMES_CHASSIS = "Teal|Coral|Periwinkle|Moss|Steel|Lavender|Obsidian|Gold|Chrome";
    string internal constant NAMES_HEAD = "Box|Rounded|Dome|Capsule|CRT|Shield";
    string internal constant NAMES_VISOR = "Dual LED|Scanner|Cyclops|Sleepy|Happy|Error|Hearts|Glitch|Laser";
    string internal constant NAMES_SIGNAL = "Amber|Cyan|Rose|Lime|White";
    string internal constant NAMES_HEADGEAR = "None|Antenna|Twin antenna|Dish|Propeller|Halo|Fins|Crown|Flame";
    string internal constant NAMES_ACCESSORY = "None|Headphones|Blush|Bolts|Seat tag|Scarf|Cracked visor|IMD pin";

    /// ids whose nonce is 1; every other id uses nonce 0. Sorted uint16 values.
    bytes internal constant OVERRIDES = hex"0224035e0520052905a105ba06ce080c08b408fe09920a050b2e0b460b5a0bc20c0c0c2e0c500c680c94";

    bytes internal constant LOGO_PALETTE = hex"0d3b36ffd23f3b3f4a5fd0b825a08bc9f4ea16695e10131f2e35578a7a3a";
    bytes internal constant LOGO_GRID = "000000000110000000000000000012210000000000000000122100000000000000001331000000000000011113311110000000001444444444410000000145665555555410000001465555555557100000114555555555571100014748998888888774100157489aa88aa8877510015748822882288775100157488888888887751000114555555555571100000145551717555710000001455555555557100000001477777777710000000001111111111000000000000000000000000000000000000000000000";
}
